# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\1\Desktop\李杨论文\断层识别论文\QTfault\QtMainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(510, 362)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 80, 72, 41))
        self.label.setObjectName("label")
        self.btButton = QtWidgets.QPushButton(self.centralwidget)
        self.btButton.setGeometry(QtCore.QRect(280, 80, 211, 261))
        self.btButton.setObjectName("btButton")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 140, 72, 41))
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 210, 101, 41))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 290, 101, 41))
        self.label_5.setObjectName("label_5")
        self.lineEdit_ker1 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_ker1.setGeometry(QtCore.QRect(170, 80, 81, 41))
        self.lineEdit_ker1.setText("")
        self.lineEdit_ker1.setObjectName("lineEdit_ker1")
        self.lineEdit_ker2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_ker2.setGeometry(QtCore.QRect(170, 140, 81, 41))
        self.lineEdit_ker2.setText("")
        self.lineEdit_ker2.setObjectName("lineEdit_ker2")
        self.lineEdit_minconn = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_minconn.setGeometry(QtCore.QRect(170, 210, 81, 41))
        self.lineEdit_minconn.setObjectName("lineEdit_minconn")
        self.lineEdit_minrem = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_minrem.setGeometry(QtCore.QRect(170, 290, 81, 41))
        self.lineEdit_minrem.setObjectName("lineEdit_minrem")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(30, 20, 111, 41))
        self.label_6.setObjectName("label_6")
        self.lineEdit_path = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_path.setGeometry(QtCore.QRect(170, 20, 331, 41))
        self.lineEdit_path.setObjectName("lineEdit_path")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "卷积核X:"))
        self.btButton.setText(_translate("MainWindow", "OK"))
        self.label_2.setText(_translate("MainWindow", "卷积核Y:"))
        self.label_4.setText(_translate("MainWindow", "最小连接距离："))
        self.label_5.setText(_translate("MainWindow", "最小移除线段："))
        self.label_6.setText(_translate("MainWindow", "sgy文件路径："))
        self.lineEdit_path.setText(_translate("MainWindow", "img01.jpg"))
